# Generated by Django 4.1.1 on 2022-10-05 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("media_api", "0002_initial"),
        ("user_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="saved_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_posts",
                to="media_api.post",
                verbose_name="Saved",
            ),
        ),
    ]
