# Generated by Django 4.0.4 on 2022-09-26 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="By",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to",
                to=settings.AUTH_USER_MODEL,
                verbose_name="To",
            ),
        ),
    ]
