# Generated by Django 4.1.1 on 2022-09-24 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_api", "0002_user_is_active_user_is_staff_alter_user_is_superuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Followers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "user_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="By",
                    ),
                ),
                (
                    "user_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="To",
                    ),
                ),
            ],
            options={
                "verbose_name": "Followers",
                "verbose_name_plural": "Followers",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="followers",
            constraint=models.CheckConstraint(
                check=models.Q(("user_from", models.F("user_to")), _negated=True),
                name="check_self_follow",
            ),
        ),
    ]
