# Generated by Django 4.1.1 on 2022-10-01 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_api", "0002_alter_followersystem_user_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followersystem",
            name="user_from",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="By",
            ),
        ),
        migrations.AlterField(
            model_name="followersystem",
            name="user_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="To",
            ),
        ),
    ]
