# Generated by Django 4.1.1 on 2022-10-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_api", "0002_user_saved_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="saved_post",
        ),
    ]
