# Generated by Django 4.0.4 on 2022-09-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_api", "0003_remove_user_check_self_follow_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="User cant followed by self",
        ),
    ]
