# Generated by Django 4.0.4 on 2022-09-26 11:01

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ("user_api", "0004_remove_user_user cant followed by self"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("user_to", django.db.models.expressions.F("user_from")),
                    _negated=True,
                ),
                name="User cant followed by self",
            ),
        ),
    ]
