# Generated by Django 4.0.4 on 2022-09-26 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_api", "0004_onlineuseractivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followers",
            name="user_from",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="By",
            ),
        ),
        migrations.AlterField(
            model_name="followers",
            name="user_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follows",
                to=settings.AUTH_USER_MODEL,
                verbose_name="To",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_avatar",
            field=models.ImageField(
                blank=True,
                default="media/default_avatar.png",
                upload_to="media/uploaded_media/",
            ),
        ),
    ]
