# Generated by Django 4.0.4 on 2022-09-26 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_api", "0005_alter_followers_user_from_alter_followers_user_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                related_name="follow_to",
                through="user_api.Followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="followers",
            name="user_from",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="By",
            ),
        ),
        migrations.AlterField(
            model_name="followers",
            name="user_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to",
                to=settings.AUTH_USER_MODEL,
                verbose_name="To",
            ),
        ),
    ]
