# Generated by Django 4.0.4 on 2022-09-26 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_api", "0007_user_is_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_activity",
            field=models.ManyToManyField(
                through="user_api.OnlineUserActivity", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
