# Generated by Django 4.0.4 on 2022-09-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_api", "0008_user_user_activity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_activity",
        ),
    ]
